// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RequirementsDBEntity;

#nullable disable

namespace RequirementsDBEntity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260808125653_Ver.0.0.1")]
    partial class Ver001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.18");

            modelBuilder.Entity("RequirementsDBEntity.Entities.Masters.RequirementsDefinition", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasComment("要求事項定義ID");

                    b.Property<string>("CreateProgram")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("create_program");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("create_user");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("RequirementDefinition")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("requirement_definition")
                        .HasComment("要求事項定義:【値例】F：機能要求 , NF：非機能要求");

                    b.Property<string>("UpdateProgram")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("update_program");

                    b.Property<string>("UpdateUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("update_user");

                    b.Property<DateTime>("UpdatedAt")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("m_requirements_definition_pkc");

                    b.ToTable("m_requirements_definition", t =>
                        {
                            t.HasComment("要求事項定義マスタ");
                        });
                });

            modelBuilder.Entity("RequirementsDBEntity.Entities.Transactions.RequirementId", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasComment("要求事項ID");

                    b.Property<string>("CreateProgram")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("create_program");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("create_user");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("RequirementDefinitionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("requirement_definition_id")
                        .HasComment("要求事項定義マスタID");

                    b.Property<string>("UpdateProgram")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("update_program");

                    b.Property<string>("UpdateUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("update_user");

                    b.Property<DateTime>("UpdatedAt")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("t_requirement_id_pkc");

                    b.ToTable("t_requirement_id", t =>
                        {
                            t.HasComment("要求事項IDテーブル");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
